"""Document renderers — pure functions, no DB."""

from __future__ import annotations

import csv
import io
import zipfile

from fpdf import FPDF
from fpdf.enums import XPos, YPos
from jinja2 import Template
from openpyxl import Workbook

from app.documents.spec import RenderContext

RISK_MEMO_TEMPLATE = """# EU AI Act Risk Classification Memo

| Field | Value |
|-------|-------|
| Assessment ID | {{ assessment_id }} |
| Generated | {{ generated_at }} |
| Company | {{ company_name }} |
| AI system | {{ system_name }} |
| Risk tier | {{ risk_tier_label }} |
| Actor role | {{ actor_role_label }} |
| Confidence | {{ confidence }} |
| Rule set version | {{ rule_version }} |
| Legal source version | {{ source_version }} |

## Executive summary

{{ executive_summary }}

## Assessment inputs

{% for label, value in answer_rows %}
- **{{ label }}:** {{ value }}
{% endfor %}

## Triggered rules

{% if triggered_rules %}
{% for rule in triggered_rules %}
### {{ rule.name }} (`{{ rule.rule_code }}`)

- **Legal basis:** {{ rule.legal_citation }}
{% if rule.legal_summary %}- **Summary:** {{ rule.legal_summary }}{% endif %}
{% if rule.source_url %}- **Source:** {{ rule.source_url }}{% endif %}
- **Rationale:** {{ rule.rationale }}

{% endfor %}
{% else %}
No rules triggered in this assessment snapshot.
{% endif %}

## Applicable obligations

{% if obligations %}
| ID | Requirement | Legal basis | Evidence | Owner |
|----|-------------|-------------|----------|-------|
{% for o in obligations %}| {{ o.obligation_id }} | {{ o.title }} | {{ o.legal_citation }} | {{ o.evidence_required or 'See obligation matrix' }} | {{ o.suggested_owner }} |
{% endfor %}
{% else %}
No seeded obligations mapped for this role and tier. Expert review recommended.
{% endif %}

## Documents included in this pack

{% for doc in required_documents %}
- {{ doc }}
{% else %}
- Risk classification memo
- AI system card
- Obligation matrix
{% endfor %}

{% if has_missing %}
## Missing information

The following inputs were not provided. Complete them before external audit or customer submission:

{% for m in missing_variables %}
- {{ m }}
{% endfor %}
{% endif %}

## Disclaimer

This memo is evidence preparation from a versioned rule engine aligned to Regulation (EU) 2024/1689 section outlines. It is not legal advice and is not a notified-body submission. Have qualified counsel review before regulatory filing.

Official legal source: **{{ legal_source_title }}** — {{ legal_source_url }}

Template sections in the evidence pack map to Annex IV, Annex V, Annex VIII, and Articles 9–18, 26, 27, 43, 47, 49, 72, and 73 where applicable.
"""

SYSTEM_CARD_TEMPLATE = """# AI System Card

One-page profile for vendor questionnaires, security reviews, and internal governance.

| | |
|---|---|
| **System** | {{ system_name }} |
| **Provider / organisation** | {{ company_name }} |
| **Assessment ID** | {{ assessment_id }} |
| **Generated** | {{ generated_at }} |

## Classification

| | |
|---|---|
| **EU AI Act risk tier** | {{ risk_tier_label }} |
| **Actor role** | {{ actor_role_label }} |
| **Classification status** | {{ classification_status }} |
| **Rule set** | v{{ rule_version }} (sources: {{ source_version }}) |

## Intended purpose and scope

{% for label, value in answer_rows %}
- **{{ label }}:** {{ value }}
{% endfor %}

## Legal basis (triggered)

{% for rule in triggered_rules %}
- {{ rule.legal_citation }}: {{ rule.legal_summary or rule.rationale }}
{% else %}
- No high-risk or transparency rules triggered in this snapshot.
{% endfor %}

## Key obligations (summary)

{% for o in obligations[:8] %}
- {{ o.title }} ({{ o.legal_citation }})
{% else %}
- Run a full assessment to map obligations.
{% endfor %}

## Human oversight and monitoring

| Item | Status |
|------|--------|
| Human oversight plan | {% if pack_sku == 'evidence_pack' %}Included in evidence pack{% else %}Available in evidence pack tier{% endif %} |
| Technical documentation (Annex IV) | {% if 'annex-iv-technical-documentation' in required_documents %}Required — template in evidence pack{% else %}Assess if high-risk provider{% endif %} |
| Logging and record-keeping | Document per Art. 12 if high-risk |

{% if has_missing %}
## Open gaps

{% for m in missing_variables %}
- ⚠ {{ m }} needs input
{% endfor %}
{% endif %}

## Contact and provenance

Generated by EU AI Act Compliance Navigator from assessment `{{ assessment_id }}`. Conclusions trace to rule set v{{ rule_version }} and legal sources {{ source_version }}.
"""


def render_markdown(ctx: RenderContext) -> bytes:
    body = Template(RISK_MEMO_TEMPLATE).render(**ctx.template_dict())
    return body.encode("utf-8")


def render_system_card(ctx: RenderContext) -> bytes:
    body = Template(SYSTEM_CARD_TEMPLATE).render(**ctx.template_dict())
    return body.encode("utf-8")


def render_obligation_csv(ctx: RenderContext) -> bytes:
    buf = io.StringIO()
    writer = csv.writer(buf)
    writer.writerow(
        [
            "obligation_id",
            "title",
            "actor_role",
            "risk_tier",
            "legal_citation",
            "legal_summary",
            "mandatory",
            "evidence_required",
            "linked_document",
            "suggested_owner",
            "status",
            "due_date",
            "enforcement_note",
            "source_url",
        ]
    )
    for o in ctx.obligations:
        writer.writerow(
            [
                o.obligation_id,
                o.title,
                ctx.primary_actor_role,
                ctx.risk_tier,
                o.legal_citation,
                o.legal_summary or "",
                "yes" if o.mandatory else "no",
                o.evidence_required or "",
                o.document_type or "",
                o.suggested_owner,
                "open",
                "",
                o.enforcement_note or "",
                o.source_url or "",
            ]
        )
    return buf.getvalue().encode("utf-8")


class _ProcurementPDF(FPDF):
    def footer(self) -> None:
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.cell(
            0,
            10,
            f"Assessment {self.assessment_id} | Page {self.page_no()}",
            new_x=XPos.LMARGIN,
            new_y=YPos.NEXT,
            align="C",
        )


def _pdf_line(pdf: FPDF, text: str, height: float = 6, *, align: str = "") -> None:
    pdf.set_x(pdf.l_margin)
    pdf.cell(0, height, text, new_x=XPos.LMARGIN, new_y=YPos.NEXT, align=align)


def _pdf_wrap(pdf: FPDF, text: str, height: float = 5) -> None:
    pdf.set_x(pdf.l_margin)
    pdf.multi_cell(0, height, text, new_x=XPos.LMARGIN, new_y=YPos.NEXT)


def render_procurement_pdf(ctx: RenderContext) -> bytes:
    """Customer-facing procurement summary for security and legal reviewers."""
    data = ctx.template_dict()
    pdf = _ProcurementPDF()
    pdf.assessment_id = ctx.assessment_id  # type: ignore[attr-defined]
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.add_page()

    pdf.set_font("Helvetica", "B", 18)
    _pdf_line(pdf, "EU AI Act Procurement Summary", 10)
    pdf.set_font("Helvetica", size=11)
    pdf.ln(2)
    _pdf_wrap(pdf, f"{ctx.system_name} | {ctx.company_name}", 6)
    pdf.ln(4)

    pdf.set_font("Helvetica", "B", 12)
    _pdf_line(pdf, "At a glance", 8)
    pdf.set_font("Helvetica", size=10)
    for line in [
        f"Risk tier: {ctx.risk_tier_label}",
        f"Actor role: {ctx.actor_role_label}",
        f"Classification: {ctx.classification_status} (confidence: {ctx.confidence or 'n/a'})",
        f"Assessment ID: {ctx.assessment_id}",
        f"Rule set v{ctx.rule_version} | Sources {ctx.source_version}",
        f"Generated: {ctx.generated_at}",
    ]:
        _pdf_line(pdf, line, 6)
    pdf.ln(4)

    pdf.set_font("Helvetica", "B", 12)
    _pdf_line(pdf, "System profile", 8)
    pdf.set_font("Helvetica", size=10)
    for label, value in ctx.answer_rows:
        _pdf_wrap(pdf, f"{label}: {value}")
    pdf.ln(2)

    pdf.set_font("Helvetica", "B", 12)
    _pdf_line(pdf, "Why this tier", 8)
    pdf.set_font("Helvetica", size=10)
    if ctx.triggered_rules:
        for rule in ctx.triggered_rules:
            pdf.set_font("Helvetica", "B", 10)
            _pdf_wrap(pdf, rule.legal_citation)
            pdf.set_font("Helvetica", size=10)
            _pdf_wrap(pdf, rule.rationale)
            pdf.ln(1)
    else:
        _pdf_wrap(pdf, "No rules triggered in this assessment.")
    pdf.ln(2)

    pdf.set_font("Helvetica", "B", 12)
    _pdf_line(pdf, "Obligations to address", 8)
    pdf.set_font("Helvetica", size=9)
    for o in ctx.obligations[:12]:
        _pdf_wrap(pdf, f"- {o.title} [{o.legal_citation}]")
    if not ctx.obligations:
        _pdf_wrap(pdf, "No obligations mapped. Request expert review.")
    pdf.ln(2)

    pdf.set_font("Helvetica", "B", 12)
    _pdf_line(pdf, "Documents in this pack", 8)
    pdf.set_font("Helvetica", size=10)
    docs = [
        "Risk classification memo (markdown)",
        "AI system card (markdown)",
        "Obligation matrix (CSV)",
        "This procurement summary (PDF)",
    ]
    if ctx.pack_sku == "evidence_pack" and ctx.is_high_risk:
        docs.extend(
            [
                "Annex IV technical documentation (Art. 11 / Annex IV)",
                "Quality management system (Art. 17)",
                "Human oversight plan (Art. 14)",
                "Instructions for use (Art. 13)",
            ]
        )
        if ctx.needs_fria:
            docs.append("FRIA template (Art. 27)")
        if ctx.needs_provider_conformity:
            docs.extend(
                [
                    "EU declaration of conformity (Art. 47 / Annex V)",
                    "EU database registration pack (Art. 49 / Annex VIII)",
                ]
            )
        docs.append("Evidence tracker (XLSX)")
    for d in docs:
        _pdf_wrap(pdf, f"- {d}")
    pdf.ln(2)

    if ctx.missing_variables:
        pdf.set_font("Helvetica", "B", 12)
        _pdf_line(pdf, "Open gaps before customer submission", 8)
        pdf.set_font("Helvetica", size=10)
        for m in ctx.missing_variables:
            _pdf_wrap(pdf, f"- {m} not provided")
        pdf.ln(2)

    source_title = ctx.legal_source_title.replace(" (Artificial Intelligence Act)", "")
    pdf.set_font("Helvetica", "I", 8)
    _pdf_wrap(
        pdf,
        "Not legal advice. Generated from a structured assessment and versioned rule engine. "
        f"Legal source: {source_title}.",
        4,
    )
    return pdf.output()


def render_docx_annex_iv(ctx: RenderContext) -> bytes:
    from app.documents.docx_builder import render_official_sections_doc
    from app.documents.official_sections import ANNEX_IV_SECTIONS, REGULATION_CITATION

    return render_official_sections_doc(
        ctx,
        title="Annex IV Technical Documentation Template",
        legal_basis=f"{REGULATION_CITATION} Article 11(1) and Annex IV",
        sections=ANNEX_IV_SECTIONS,
    )


def render_docx_qms(ctx: RenderContext) -> bytes:
    from app.documents.docx_builder import render_bullet_checklist_doc
    from app.documents.official_sections import ARTICLE_17_QMS, REGULATION_CITATION

    return render_bullet_checklist_doc(
        ctx,
        title="Quality Management System Template",
        legal_basis=f"{REGULATION_CITATION} Article 17",
        bullets=ARTICLE_17_QMS,
    )


def render_docx_oversight(ctx: RenderContext) -> bytes:
    from app.documents.docx_builder import render_bullet_checklist_doc
    from app.documents.official_sections import ARTICLE_14_OVERSIGHT, REGULATION_CITATION

    return render_bullet_checklist_doc(
        ctx,
        title="Human Oversight Plan Template",
        legal_basis=f"{REGULATION_CITATION} Article 14",
        bullets=ARTICLE_14_OVERSIGHT,
    )


def render_docx_instructions(ctx: RenderContext) -> bytes:
    from app.documents.docx_builder import render_bullet_checklist_doc
    from app.documents.official_sections import ARTICLE_13_INSTRUCTIONS, REGULATION_CITATION

    return render_bullet_checklist_doc(
        ctx,
        title="Instructions for Use Template",
        legal_basis=f"{REGULATION_CITATION} Article 13",
        bullets=ARTICLE_13_INSTRUCTIONS,
    )


def render_docx_fria(ctx: RenderContext) -> bytes:
    from app.documents.docx_builder import render_bullet_checklist_doc
    from app.documents.official_sections import ARTICLE_27_FRIA, REGULATION_CITATION

    return render_bullet_checklist_doc(
        ctx,
        title="Fundamental Rights Impact Assessment (FRIA) Template",
        legal_basis=f"{REGULATION_CITATION} Article 27",
        bullets=ARTICLE_27_FRIA,
    )


def render_docx_declaration(ctx: RenderContext) -> bytes:
    from app.documents.docx_builder import render_numbered_list_doc
    from app.documents.official_sections import ANNEX_V_ITEMS, REGULATION_CITATION

    return render_numbered_list_doc(
        ctx,
        title="EU Declaration of Conformity (Annex V Skeleton)",
        legal_basis=f"{REGULATION_CITATION} Article 47 and Annex V",
        numbered_items=ANNEX_V_ITEMS,
    )


def render_annex_viii_csv(ctx: RenderContext) -> bytes:
    from app.documents.official_sections import ANNEX_VIII_SECTION_A_FIELDS

    buf = io.StringIO()
    writer = csv.writer(buf)
    writer.writerow(["field_id", "field_label", "value", "legal_basis"])
    basis = "Regulation (EU) 2024/1689 Annex VIII Section A (Art. 49(1))"
    for field_id, label in ANNEX_VIII_SECTION_A_FIELDS:
        value = ""
        if field_id == "1":
            value = ctx.company_name
        elif field_id == "4":
            value = ctx.system_name
        elif field_id == "5":
            from app.documents.labels import format_answer_value

            value = format_answer_value(
                "use_case_category", ctx.answers.get("use_case_category")
            )
        writer.writerow([field_id, label, value, basis])
    return buf.getvalue().encode("utf-8")


def render_evidence_xlsx(ctx: RenderContext) -> bytes:
    wb = Workbook()
    ws = wb.active
    ws.title = "Evidence Tracker"
    ws.append(
        [
            "evidence_id",
            "obligation_id",
            "requirement",
            "legal_citation",
            "artifact",
            "status",
            "owner",
            "notes",
        ]
    )
    artifact_map = {
        "risk_classification_memo": "01_risk_classification_memo.md",
        "annex-iv-technical-documentation": "04_annex_iv_technical_documentation_template.docx",
        "quality-management-system": "05_quality_management_system_template.docx",
        "human-oversight-plan": "06_human_oversight_plan_template.docx",
        "instructions-for-use": "07_instructions_for_use_template.docx",
        "fria-template": "08_fria_template.docx",
        "eu-declaration-of-conformity": "09_eu_declaration_of_conformity_skeleton.docx",
        "eu-database-registration": "10_eu_database_registration_data_pack.csv",
    }
    for i, o in enumerate(ctx.obligations, start=1):
        artifact = artifact_map.get(o.document_type or "", o.document_type or "manual evidence")
        ws.append(
            [
                f"EV-{i:03d}",
                o.obligation_id,
                o.title,
                o.legal_citation,
                artifact,
                "draft",
                o.suggested_owner,
                o.evidence_required or "",
            ]
        )
    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()


def build_zip(files: dict[str, bytes]) -> bytes:
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        for name, data in files.items():
            zf.writestr(name, data)
    return buf.getvalue()


# Backwards-compatible aliases
render_pdf = render_procurement_pdf
build_evidence_pack_zip = build_zip
build_starter_report_zip = build_zip
