steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - deploy/cloudrun/web.Dockerfile
      - -t
      - $_IMAGE
      - --build-arg
      - NEXT_PUBLIC_API_URL=$_NEXT_PUBLIC_API_URL
      - --build-arg
      - NEXT_PUBLIC_WEB_URL=$_NEXT_PUBLIC_WEB_URL
      - --build-arg
      - NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION=$_NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION
      - --build-arg
      - NEXT_PUBLIC_GA_MEASUREMENT_ID=$_NEXT_PUBLIC_GA_MEASUREMENT_ID
      - --build-arg
      - NEXT_PUBLIC_POSTHOG_KEY=$_NEXT_PUBLIC_POSTHOG_KEY
      - --build-arg
      - NEXT_PUBLIC_POSTHOG_HOST=$_NEXT_PUBLIC_POSTHOG_HOST
      - .
images:
  - $_IMAGE
